- type: http
  enabled: true
  id: SimpleHTTP
  urls: http://www.google.com
  schedule: "@every 15s"
  name: Simple HTTP
- type: browser
  enabled: true
  id: my-monitor
  name: My Monitor
  source:
    inline:
      script:
        step("load homepage", async () => {
            await page.goto('https://www.elastic.co');
        });
  schedule: "@every 1m"
